### ISSUE TITLE
return assets with tile

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler-mosaic#11]
It could be nice to be able to return a list of assets used per tiles

In https://github.com/cogeotiff/rio-tiler-mosaic/blob/bde4ffee51b0387b366450aaf4954af894d06573/rio_tiler_mosaic/mosaic.py#L85-L102

we could replace `tiler` with 
```python
def wrapper(asset, tile_x=tile_x, tile_y=tile_y, tile_z=tile_z, **kwargs):
    return tiler(asset, tile_x=tile_x, tile_y=tile_y, tile_z=tile_z, **kwargs) + (asset,)
```

This means the pixel selection methods will need to handler a third input (tile, mask, asset)

**Comment by kylebarron** [comment]
This is now possible with `rio_tiler.mosaic.reader.mosaic_reader` on master, to be released in `rio-tiler` v2.
